//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.40607.16
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace SystemDotNet.Reporter
{
    using System;
    using System.IO;
    using System.Resources;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the Strongly Typed Resource Builder
    // class via a tool like ResGen or Visual Studio.NET.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    class Resources {
        
        private static System.Resources.ResourceManager _resMgr;
        
        private static System.Globalization.CultureInfo _resCulture;
        
        /*FamANDAssem*/ internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if ((_resMgr == null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SystemDotNet.Console.Resources", typeof(Resources).Assembly);
                    _resMgr = temp;
                }
                return _resMgr;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return _resCulture;
            }
            set {
                _resCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap companies {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("companies", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap day {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("day", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap notes {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("notes", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap open {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("open", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap props {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("props", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap save {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("save", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap settings {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("settings", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap settings1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("settings1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap tasks {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("tasks", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap toasc {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("toasc", _resCulture)));
            }
        }
    }
}
